# ----
# Markdown
kramdown:
  input: GFM
  highlighter: rouge

 
# Site

title: Página de Javier Cancela
url: https://www.javiercancela.com
baseurl:
google_maps_javascript_api_key:
future: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Página personal de Javier Cancela
author:
  name: Javier Cancela
  email: javier.cancela.vicente@gmail.com
  twitter: javier_cancela_
social:
  name: Javier Cancela
  links:
    - https://github.com/javiercancela/javiercancela.github.io

# -----
# Build

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/:num/"

jekyll-archives:
  enabled: all
    

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person